# Generated by Django 5.0.6 on 2024-07-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_class_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
