# Generated by Django 5.0.6 on 2024-07-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_class_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
